export enum MessageType {
  JOIN = "JOIN",
  NEW_MESSAGE = "NEW_MESSAGE",
  REQUEST_APPROVED = "REQUEST_APPROVED",
  NEW_FRIEND_REQUEST = "NEW_FRIEND_REQUEST",
  REQUEST_CANCELLED = "REQUEST_CANCELLED",
  FRIENDSHIP_DELETED = "FRIENDSHIP_DELETED",
  FRIEND_UPDATED_IMG = "FRIEND_UPDATED_IMG",
}
